use_frameworks!

platform :ios, '10.0'

target 'DSExpandableHasTagLabel_Example' do
  pod 'DSExpandableHasTagLabel', :path => '../'

  target 'DSExpandableHasTagLabel_Tests' do
    inherit! :search_paths

    
  end
end
